[build]
  command = "echo 'No build needed for static site'"
  publish = "/"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  framework = "#custom"
  targetPort = 3000
  publish = "/"
